
import sys

file_path = r'c:\Users\Administrator\Downloads\KK-Studio-1.0.0\src\App.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Search for the function signature
expected_start = "  const executeGeneration = useCallback(async (node: PromptNode) => {"
start_idx = -1
for i, line in enumerate(lines):
    if expected_start in line:
        start_idx = i
        break

if start_idx == -1:
    print("ERROR: Could not find function signature.")
    sys.exit(1)

# Find end of function
end_marker = "}, [isMobile, updatePromptNode, addPromptNode, addImageNodes, activeCanvas, activeSourceImage, getCardDimensions]);"
end_idx = -1
for i in range(start_idx, len(lines)):
    if end_marker in lines[i]:
        end_idx = i
        break

if end_idx == -1:
    print("ERROR: Could not find function end marker.")
    sys.exit(1)

print(f"Found executeGeneration from index {start_idx} to {end_idx}")

# The complete fixed function
fixed_function = [
    "  const executeGeneration = useCallback(async (node: PromptNode) => {\n",
    "    const { id: promptNodeId, prompt: promptToUse, parallelCount: count = 1, model: initialModel, mode, referenceImages: files = [] } = node;\n",
    "    let effectiveModel = initialModel;\n",
    "    let successResults: GeneratedImage[] = [];\n",
    "\n",
    "    // 🚀 [Critical Fix] Define finalPos at a higher scope to ensure Error cards also land at latest center\n",
    "    let finalPos = node.position;\n",
    "\n",
    "    // [FIX] Get fresh position from canvas state to support moving during generation\n",
    "    // ✅ 使用ref获取最新状态,避免闭包问题\n",
    "    const freshCanvas = activeCanvasRef.current;\n",
    "    const liveNode = freshCanvas?.promptNodes.find(n => n.id === promptNodeId);\n",
    "\n",
    "    // 🚀 [修复] 如果找不到节点，使用传入的 node 参数作为后备\n",
    "    if (!liveNode) {\n",
    "      console.warn('[executeGeneration] Node not found in canvas, using original node as fallback:', promptNodeId);\n",
    "    }\n",
    "\n",
    "    const taskNode = liveNode || node;\n",
    "    const isVideo = mode === GenerationMode.VIDEO;\n",
    "\n",
    "    // 🚀 [Safe State Tracking] Track success to prevent error overwrite\n",
    "\n",
    "    try {\n",
    "      const buildTask = (index: number) => async () => {\n",
    "        const startTime = Date.now();\n",
    "        const currentRequestId = `${promptNodeId}-${index}`;\n",
    "\n",
    "        // Timeout Check (4 minutes)\n",
    "        let isFinished = false;\n",
    "        const timeoutId = setTimeout(() => {\n",
    "          if (!isFinished) {\n",
    "            cancelGeneration(currentRequestId);\n",
    "            updatePromptNode({\n",
    "              ...node,\n",
    "              isGenerating: false,\n",
    "              error: '生成超时，请重新发送任务'\n",
    "            });\n",
    "            import('./services/notificationService').then(({ notify }) => {\n",
    "              notify.warning('生成超时', '已超过4分钟，任务已自动停止。请检查网络后重试。');\n",
    "            });\n",
    "          }\n",
    "        }, 240000);\n",
    "\n",
    "        try {\n",
    "          let generatedBase64 = '';\n",
    "          let videoUrl = '';\n",
    "          let tokenUsage = 0;\n",
    "          let costUsd = 0;\n",
    "          let currentAspectRatio = node.aspectRatio;\n",
    "          let currentSize = node.imageSize;\n",
    "          let exactDimensions = undefined;\n",
    "          let provider = undefined;\n",
    "          let providerLabel = undefined;\n",
    "          let modelLabel = undefined;\n",
    "\n",
    "          if (isVideo) {\n",
    "            const { generateVideo } = await import('./services/videoService');\n",
    "            const apiKey = keyManager.getSlots().find(s => !s.disabled && s.status === 'valid')?.key;\n",
    "            if (!apiKey) {\n",
    "              throw new Error('没有可用的 API Key');\n",
    "            }\n",
    "            const videoAspect = node.aspectRatio === '9:16' ? '9:16' : '16:9';\n",
    "            const videoResolution = (() => {\n",
    "              const size = node.imageSize?.toLowerCase() || '';\n",
    "              if (size.includes('4k') || size.includes('ultra')) return '4k';\n",
    "              if (size.includes('1080') || size.includes('hd')) return '1080p';\n",
    "              return '720p';\n",
    "            })();\n",
    "            const videoResult = await generateVideo(\n",
    "              {\n",
    "                prompt: promptToUse,\n",
    "                aspectRatio: videoAspect,\n",
    "                resolution: videoResolution,\n",
    "                referenceImages: files.length > 0\n",
    "                  ? files.slice(0, 3).map(f => f.data.replace(/^data:image\\/[^;]+;base64,/, ''))\n",
    "                  : undefined\n",
    "              },\n",
    "              apiKey\n",
    "            );\n",
    "            videoUrl = videoResult.videoUrl;\n",
    "            costUsd = effectiveModel.toLowerCase().includes('fast') ? 0.15 : 0.30;\n",
    "          } else {\n",
    "            const result = await generateImage(\n",
    "              promptToUse, node.aspectRatio, node.imageSize, files, effectiveModel, '', currentRequestId, false\n",
    "            );\n",
    "            generatedBase64 = result.url;\n",
    "            tokenUsage = result.tokens || 0;\n",
    "            costUsd = result.cost || 0;\n",
    "            if (result.model) effectiveModel = result.model;\n",
    "            if (result.imageSize) currentSize = result.imageSize;\n",
    "            if (result.aspectRatio) currentAspectRatio = result.aspectRatio;\n",
    "            if (result.dimensions) exactDimensions = result.dimensions;\n",
    "            if (result.provider) provider = result.provider;\n",
    "            if (result.providerName) providerLabel = result.providerName;\n",
    "            if (result.modelName) modelLabel = result.modelName;\n",
    "          }\n",
    "\n",
    "          isFinished = true;\n",
    "          clearTimeout(timeoutId);\n",
    "          const generationTime = Date.now() - startTime;\n",
    "\n",
    "          let displayUrl = generatedBase64;\n",
    "          let originalUrl = generatedBase64;\n",
    "          if (generatedBase64.startsWith('http')) {\n",
    "            try {\n",
    "              const res = await fetch(generatedBase64);\n",
    "              if (res.ok) {\n",
    "                const blob = await res.blob();\n",
    "                const blobUrl = URL.createObjectURL(blob);\n",
    "                displayUrl = blobUrl;\n",
    "                originalUrl = blobUrl;\n",
    "                generatedBase64 = blobUrl;\n",
    "              }\n",
    "            } catch (e) { console.warn('Blob fetch failed', e); }\n",
    "          }\n",
    "\n",
    "          if (isVideo) { displayUrl = videoUrl; originalUrl = videoUrl; }\n",
    "\n",
    "          return {\n",
    "            index, url: displayUrl, originalUrl, generationTime, base64: generatedBase64, mode,\n",
    "            tokens: tokenUsage, cost: costUsd, effectiveModel, effectiveSize: currentSize,\n",
    "            effectiveAspectRatio: currentAspectRatio, exactDimensions, provider,\n",
    "            providerName: providerLabel, modelName: modelLabel\n",
    "          };\n",
    "        } catch (error) {\n",
    "          isFinished = true;\n",
    "          clearTimeout(timeoutId);\n",
    "          return { error: error.message || 'Unknown error' };\n",
    "        }\n",
    "      };\n",
    "\n",
    "      const tasks = Array.from({ length: count }).map((_, index) => buildTask(index));\n",
    "      const runWithConcurrency = async (taskList, limit) => {\n",
    "        const results = new Array(taskList.length);\n",
    "        let nextIndex = 0;\n",
    "        const workers = Array.from({ length: Math.max(1, limit) }).map(async () => {\n",
    "          while (nextIndex < taskList.length) {\n",
    "            const current = nextIndex;\n",
    "            nextIndex += 1;\n",
    "            results[current] = await taskList[current]();\n",
    "          }\n",
    "        });\n",
    "        await Promise.all(workers);\n",
    "        return results;\n",
    "      };\n",
    "\n",
    "      const imageData = await runWithConcurrency(tasks, count);\n",
    "      const validImageData = imageData.filter(d => d && !d.error);\n",
    "\n",
    "      if (validImageData.length === 0) {\n",
    "        throw new Error(imageData[0]?.error || '所有图片生成失败');\n",
    "      }\n",
    "\n",
    "      // ✅ [Critical Fix] Re-calculate Center to support Canvas Pan during generation\n",
    "      const finalCanvas = activeCanvasRef.current;\n",
    "      const latestNode = finalCanvas?.promptNodes.find(n => n.id === promptNodeId);\n",
    "      const effectiveNodeForPos = latestNode || taskNode || node;\n",
    "\n",
    "      const currentTransform = canvasRef.current?.getCurrentTransform() || canvasTransform;\n",
    "      const viewportRect = canvasRef.current?.getCanvasRect() || null;\n",
    "      const leftOffset = isSidebarOpen && !isMobile ? 260 : (isMobile ? 0 : 60);\n",
    "      const rightOffset = isChatOpen && !isMobile ? 420 : 0;\n",
    "      const latestCenter = getViewportPreferredPosition(currentTransform, viewportRect, 180, { left: leftOffset, right: rightOffset });\n",
    "\n",
    "      const shouldAutoCenter = !effectiveNodeForPos.userMoved && !effectiveNodeForPos.sourceImageId;\n",
    "\n",
    "      // 🛡️ [NaN Guard]\n",
    "      const safeCenter = {\n",
    "        x: isFinite(latestCenter.x) ? latestCenter.x : node.position.x,\n",
    "        y: isFinite(latestCenter.y) ? latestCenter.y : node.position.y\n",
    "      };\n",
    "\n",
    "      finalPos = shouldAutoCenter ? safeCenter : (latestNode?.position || effectiveNodeForPos.position);\n",
    "\n",
    "      // 🛡️ [Anti-Zero-Bug]\n",
    "      if (finalPos.x === 0 && finalPos.y === 0 && (node.position.x !== 0 || node.position.y !== 0)) {\n",
    "        finalPos = node.position;\n",
    "      }\n",
    "\n",
    "      const gapToImages = 80;\n",
    "      const gap = 20;\n",
    "      const { width: cardWidth, totalHeight: cardHeight } = getCardDimensions(node.aspectRatio, true);\n",
    "\n",
    "      const results = validImageData.map((item, idx) => {\n",
    "        const { url, originalUrl, generationTime, base64, tokens, cost, effectiveModel: resModel, effectiveSize: resSize, effectiveAspectRatio: resRatio, exactDimensions, provider, providerName, modelName } = item;\n",
    "        const finalModel = resModel || effectiveModel;\n",
    "        const finalSize = resSize || node.imageSize;\n",
    "        const finalAspectRatio = resRatio || node.aspectRatio;\n",
    "\n",
    "        const columns = 2;\n",
    "        const col = idx % columns;\n",
    "        const row = Math.floor(idx / columns);\n",
    "        const totalCards = validImageData.length;\n",
    "        const cardsInCurrentRow = Math.min(columns, totalCards - row * columns);\n",
    "\n",
    "        let x, y;\n",
    "        if (isMobile) {\n",
    "          const mobileCardWidth = 170, mobileCardHeight = 260, mobileGap = 10;\n",
    "          const rowWidth = cardsInCurrentRow * mobileCardWidth + (cardsInCurrentRow - 1) * mobileGap;\n",
    "          x = finalPos.x + (-rowWidth / 2 + col * (mobileCardWidth + mobileGap) + mobileCardWidth / 2);\n",
    "          y = finalPos.y + (gapToImages + mobileCardHeight + row * (mobileCardHeight + mobileGap));\n",
    "        } else {\n",
    "          const rowWidth = cardsInCurrentRow * cardWidth + (cardsInCurrentRow - 1) * gap;\n",
    "          x = finalPos.x + (-rowWidth / 2 + col * (cardWidth + gap) + cardWidth / 2);\n",
    "          y = finalPos.y + (gapToImages + cardHeight + row * (cardHeight + gap));\n",
    "        }\n",
    "\n",
    "        const uniqueId = Date.now().toString() + idx + Math.random();\n",
    "        if (base64) saveImage(uniqueId, base64).catch(() => {});\n",
    "\n",
    "        return {\n",
    "          id: uniqueId, url, originalUrl, prompt: promptToUse, aspectRatio: finalAspectRatio,\n",
    "          imageSize: finalSize, timestamp: Date.now(), model: finalModel,\n",
    "          modelLabel: modelName || finalModel, provider, providerLabel: providerName || provider,\n",
    "          mode, canvasId: activeCanvas?.id || 'default', parentPromptId: promptNodeId, position: { x, y },\n",
    "          dimensions: isVideo ? `${finalAspectRatio} · 720p` : `${finalAspectRatio} · ${finalSize || '1K'}`,\n",
    "          generationTime, tokens, cost, exactDimensions\n",
    "        };\n",
    "      });\n",
    "\n",
    "      successResults = results;\n",
    "      updatePromptNode({\n",
    "        ...effectiveNodeForPos, position: finalPos, isGenerating: false, childImageIds: results.map(r => r.id), isDraft: false\n",
    "      });\n",
    "      addImageNodes(results);\n",
    "\n",
    "      import('./services/costService').then(({ recordCost }) => {\n",
    "        recordCost(successResults[0]?.model || effectiveModel, successResults[0]?.imageSize || node.imageSize, successResults.length, promptToUse, files.length);\n",
    "      });\n",
    "\n",
    "      if (activeSourceImage && activeSourceImage === effectiveNodeForPos.sourceImageId) setActiveSourceImage(null);\n",
    "\n",
    "    } catch (err) {\n",
    "      console.error('[executeGeneration] Error:', err);\n",
    "      if (successResults.length > 0) {\n",
    "        const currentCanvas = activeCanvasRef.current;\n",
    "        const currentNode = currentCanvas?.promptNodes.find(n => n.id === node.id) || node;\n",
    "        updatePromptNode({ ...currentNode, isGenerating: false });\n",
    "        return;\n",
    "      }\n",
    "\n",
    "      const currentCanvas = activeCanvasRef.current;\n",
    "      const currentNode = currentCanvas?.promptNodes.find(n => n.id === node.id) || node;\n",
    "      const errorNode = { ...currentNode, position: finalPos, isGenerating: false, error: err.message || 'Failed' };\n",
    "      const existsInCanvas = currentCanvas?.promptNodes.some(n => n.id === node.id);\n",
    "\n",
    "      if (existsInCanvas) updatePromptNode(errorNode);\n",
    "      else await addPromptNode(errorNode);\n",
    "\n",
    "      import('./services/notificationService').then(({ notify }) => {\n",
    "        notify.error('生成任务失败', err.message || \"Generation failed.\");\n",
    "      });\n",
    "      if (err.message && (err.message.includes(\"API Key\") || err.message.includes(\"403\"))) {\n",
    "        setShowSettingsPanel(true);\n",
    "        setSettingsInitialView('api-management');\n",
    "      }\n",
    "    }\n",
    "  }, [isMobile, updatePromptNode, addPromptNode, addImageNodes, activeCanvas, activeSourceImage, getCardDimensions]);\n"
]

# Replace lines
lines[start_idx : end_idx + 1] = fixed_function

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Successfully injected fixed executeGeneration.")
